### ISSUE TITLE
Allow the user to manually specify an e-mail address

### ISSUE THREAD

**Issue by babastars** [bilalcaliskan/oreilly-trial#86] opened 2022-10-31 18:47 UTC
In order to bypass errors like ""Email address is undeliverable." - it would be great if the program had a "manual mode" in which the user can specify his own email and pass combination.

**Comment by bilalcaliskan** [comment] 2022-11-01 18:41
hello @babastars , first of all thank you for your attention. 

The purpose of that project was providing reproducible account creation but lastly even if i created temp emails and registered with them, Oreilly now only accepts popular email domains like gmail, outlook etc i guess. Still thinking on possible workaround about that problem but i will implement your idea as a last resort since there is nothing to do left :/

**Comment by bilalcaliskan** [comment] 2022-11-19 12:02
@babastars this is resolved by #91. Cheers :clinking_glasses:

**Closed as completed by bilalcaliskan** 2022-11-19 12:02 UTC
